Remove and .gitignore `resources` directory
CodeBuild was getting an error:

```
Error: Error building site: TOCSS: failed to transform "ananke/css/main.css" (text/css): resource "css/ananke/css/main.css_af7eae7717e76be05924f27bac629e80" not found in file cache
```

I suspect this is because an earlier version of the Ananke CSS file was
being cached, but the submodule pulled in a new Ananke commit that
requires a new version. Perhaps? Who knows. I cannot replicate the
problem locally, so I need to push-to-test the behaviour in CodeBuild :(